import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useTranslation } from "next-i18next";
import Menu from "../components/Menu";
import Landing from "../components/Landing";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero";
import Section from "../components/Section";
import Skills from "../components/Skills";
import React from "react";

export default function Home() {
  const { t } = useTranslation();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu t={t} />

      <Landing heading={t("landing:heading")} tagline={t("landing:tagline")} />

      <Hero
        id="about"
        image={"/images/me.png"}
        heading={t("about:heading")}
        tagline={t("about:tagline")}
        description={t("about:about")}
      />

      <Skills id="technical_skills" t={t} />

      <Section
        heading={t("portfolio:heading")}
        tagline={t("portfolio:tagline")}
      ></Section>

      <Footer />
    </div>
  );
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        "navbar",
        "landing",
        "about",
        "portfolio",
        "skills"
      ]))
    }
  };
}
