import Head from "next/head";
import Landing from "../components/Landing";
import styles from "../styles/Home.module.css";

export default function Home() {
  const landing = {
    heading: "Mohammad Abd Alrahman",
    tagline: "Full Stack Developer"
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing heading={landing.heading} tagline={landing.tagline} />
    </div>
  );
}
